name: talentintel_ai
description: "AI Talent Intelligence - NCF-based KPI Performance Prediction"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^15.1.2

  # Dependency Injection
  get_it: ^8.0.3

  # UI & Design
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.20.2
  gap: ^3.0.1
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  file_picker: ^11.0.2
  printing: ^5.14.3
  pdf: ^3.12.0
  shared_preferences: ^2.5.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
