// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OukWYN5UMQl1r-Ffii2BQioyv24wS7s',
    appId: '1:734159347540:web:063b6ccd175863fb0df2c1',
    messagingSenderId: '734159347540',
    projectId: 'kpi-project-kelompok-2',
    authDomain: 'kpi-project-kelompok-2.firebaseapp.com',
    storageBucket: 'kpi-project-kelompok-2.firebasestorage.app',
    measurementId: 'G-4BLLQ1Y22T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_h4_MkVKaheOb4Xxffs9KJEoWy5AOpE',
    appId: '1:734159347540:android:13524913cfbc4e7a0df2c1',
    messagingSenderId: '734159347540',
    projectId: 'kpi-project-kelompok-2',
    storageBucket: 'kpi-project-kelompok-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKYhYCpDjxN6S1M53hDWoJ2N2rJElSs0g',
    appId: '1:734159347540:ios:4940d2f0ab474b0d0df2c1',
    messagingSenderId: '734159347540',
    projectId: 'kpi-project-kelompok-2',
    storageBucket: 'kpi-project-kelompok-2.firebasestorage.app',
    iosBundleId: 'com.talentintel.talentintelAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5OukWYN5UMQl1r-Ffii2BQioyv24wS7s',
    appId: '1:734159347540:web:19ab2e4bb1eef0f70df2c1',
    messagingSenderId: '734159347540',
    projectId: 'kpi-project-kelompok-2',
    authDomain: 'kpi-project-kelompok-2.firebaseapp.com',
    storageBucket: 'kpi-project-kelompok-2.firebasestorage.app',
    measurementId: 'G-ZC6CNY2LNX',
  );
}
